package CS1632_Deliverable3.tests;

import static org.junit.Assert.*;

import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.htmlunit.HtmlUnitDriver;

/**
As a non-English speaker
I want Wikipedia articles in my native language(s)
So that I can understand the article better
 *
 */

public class TestLanguage {

	static WebDriver driver = new HtmlUnitDriver();
	
	/*
	Given that I am on the main page
	When I click on the link "Espanol"
	Then I will be redirect to Spanish Wikipedia page
	*/
	@Test
	public void TestSpanishMainPage_ClickFromNavPanel() {
		//get main page
		driver.get("https://www.wikipedia.org");
		//this weird stuff is generated by selenium IDE, it works though
		driver.findElement(By.cssSelector("div.central-featured-lang.lang2 > a.link-box > strong")).click();
		//get the correct div with the given id -> get the attribute inside
		WebElement e = driver.findElement(By.id("mw-content-text"));
		String lang = e.getAttribute("lang");
		//assert
		assertEquals(lang,"es");
	}
	
	/*
	Given that I open a browser or tab
	When I access Wikipedia page with Spanish prefix in the address
	Then I will be redirect to Spanish Wikipedia page
	*/
	@Test
	public void TestSpanishMainPage_TypeInAddress() {
		//get main page
		driver.get("https://es.wikipedia.org");
		//get the correct div with the given id -> get the attribute inside
		WebElement e = driver.findElement(By.id("mw-content-text"));
		String lang = e.getAttribute("lang");
		//assert
		assertEquals(lang,"es");
	}
	
	/*
	Given that I am on an Ensligh Wikipedia article which offer Spanish translation
	When I click on the link to Spanish translation
	Then I will be redirect to Spanish article of the original article
	*/
	@Test
	public void TestSpanishArticle_FromEnglishArticle() {
		//get the english article about StarCraft
		driver.get("https://en.wikipedia.org/wiki/Starcraft");
		//click on the Spanish translation
		driver.findElement(By.linkText("Español")).click();

		//get language attribute
		WebElement e = driver.findElement(By.id("mw-content-text"));
		String lang = e.getAttribute("lang");
		//assert!
		assertEquals(lang,"es");
	}
	
	
	/*
	Given that I open a brower or a tab
	When I type the English wikipedia article, with Spanish prefix in the address
	Then I will be redirect to Spanish article of the original article
	*/
	@Test
	public void TestSpanishArticle_FromEnglishArticle_TypeInAddress() {
		//get the Spanish article about StarCraft
		driver.get("https://es.wikipedia.org/wiki/Starcraft");

		//get language attribute
		WebElement e = driver.findElement(By.id("mw-content-text"));
		String lang = e.getAttribute("lang");
		//assert!
		assertEquals(lang,"es");
	}
	
	/*
	Given that I am on a non-Spanish wikipedia article which does not offer Spanish translation
	When I try to add Spanish prefix in the article's address
	Then I will be notified the article does not exist
	*/
	@Test
	public void TestSpanishArticle_NoArticlesFound() {
		//get the Spanish article about a Vietnamese Singer
		driver.get("https://es.wikipedia.org/wiki/Son_Tung_M-TP");

		//of couse there is no Spanish article about him, hence:
		try
		{
			WebElement e = driver.findElement(By.id("noarticletext"));
			assertTrue(e.isDisplayed());
		}
		catch (NoSuchElementException e)
		{
			fail();
		}
	}
}